### GET /logs
GET http://localhost:3000/logs

### POST /logs
POST http://localhost:3000/logs
Content-Type: application/json

{
    "user_agent": "Agent 1",
    "response_time": 100
}

### GET /csv
GET http://localhost:3000/csv

### POST /csv
POST http://localhost:3000/csv
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="a.csv"
Content-Type: text/csv

< ./test-logs.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--